# Custom Language File for Launcher Customizer

[ejs.app]
title = "EarthLink Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/darklink973/EarthLinkLauncher"
mediaDiscordURL = "https://discord.gg/QDykKMpf74"

[ejs.settings]
sourceGithubLink = "https://github.com/darklink973/EarthLinkLauncher/"
supportLink = "https://github.com/darklink973/EarthLinkLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Earthlink !"
welcomeDescription = "EarthLink est un serveur semi rp. Le but est simple, conquerir le monde !"
welcomeDescCTA = "Vous y êtes presque !"
